# Generated by Django 4.2.11 on 2024-06-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together={('chromosome', 'coordinate', 'sample')},
        ),
    ]
