# Generated by Django 4.2.11 on 2024-04-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_created_at_comment_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
