# Generated by Django 4.2.11 on 2024-05-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='alt',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('T', 'T'), ('G', 'G')], max_length=1),
        ),
        migrations.AlterField(
            model_name='snp',
            name='ref',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C'), ('T', 'T'), ('G', 'G')], max_length=1),
        ),
    ]
